name: Step 3, Upload test reports

# This step triggers after push to the ci.yml file on the ci branch
# This step sets STEP to 4
# This step closes <details id=3> and opens <details id=4>

# This will run every time we push to the ci.yml file on the ci branch
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - ci
    paths:
      - .github/workflows/ci.yml

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail

      - uses: actions/upload-artifact@main
        with:
          name: remark-lint-report
          path: public/
